import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata = {
  title: "StudyNook",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#1B1411",
              color: "#F7EBDD",
              border: "1px solid #4A3528",
            },
            success: {
              iconTheme: { primary: "#E0B07A", secondary: "#1B1411" },
            },
            error: {
              iconTheme: { primary: "#f87171", secondary: "#1B1411" },
            },
          }}
        />
        <Footer></Footer>
      </body>
    </html>
  );
}
